name=Forgetfulino
version=0.1.0
author=Nader Al Khatib
maintainer=Nader Al Khatib
sentence=Embed and retrieve Arduino sketch source code directly from firmware.
paragraph=Forgetfulino stores the original sketch source code in flash memory so it can be recovered later through Serial.
category=Other
url=https://github.com/IamTheVector/Forgetfulino
architectures=*
license=MIT